/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TouchingButton {
    }
}
declare global {
    interface HTMLTouchingButtonElement extends Components.TouchingButton, HTMLStencilElement {
    }
    var HTMLTouchingButtonElement: {
        prototype: HTMLTouchingButtonElement;
        new (): HTMLTouchingButtonElement;
    };
    interface HTMLElementTagNameMap {
        "touching-button": HTMLTouchingButtonElement;
    }
}
declare namespace LocalJSX {
    interface TouchingButton {
    }
    interface IntrinsicElements {
        "touching-button": TouchingButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "touching-button": LocalJSX.TouchingButton & JSXBase.HTMLAttributes<HTMLTouchingButtonElement>;
        }
    }
}
